apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1" 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.mysql.storageClass }}
  resources:
    requests:
      storage: {{ .Values.mysql.storage }}